### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Sparh4wk** [torenado/plugin.video.animestream#1]
Hi,

your addon looks great, but I have a problem with install.
It tells me that dependencies are missing.. but I cant find anyway on git which dependencies are needed to run this great addon.

Can you please list the here?

Thanks

**Comment by torenado** [comment]
Sorry for the long time to respond. I'll check this out this weekend. I've been making mods to the code and have not been keeping up with the installation. From memory, I would say you need urlresovler and cacheCommon. I'll get better confirmation when I get home. 

A quick way to check for dependencies is to review the addin.xml file. 

Regards

**Comment by torenado** [comment]
Here are the dependencies:

script.common.plugin.cache
script.module.urlresolver
script.service.animestream <-- newly added

I've also noticed that my new architecture has slowed down the whole metadata grabbing process.  I'm in the process of converting to fully utilizing sqlite for data caching purposes as a way to speed up this process.  However, I'll be unable to get back to coding until August.
